activity/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

activity/todolist/urls.py
from django.urls import path
from . import views

app_name = 'todolist'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:todoitem_id>/', views.todoitem, name = 'viewtodoitem'),
    path('register/', views.register, name = 'register'),
    path('change_password/', views.change_password, name = 'change_password'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('add_task/', views.add_task, name = 'add_task'),
    path('<int:todoitem_id>/edit/', views.update_task, name = 'update_task'),
    path('<int:todoitem_id>/delete/', views.delete_task, name = 'delete_task'),
]

activity/todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoItem(models.Model):
    task_name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    status = models.CharField(max_length=50, default='pending')
    date_created = models.DateTimeField('date_created')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

activity/todolist/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = 'Username', max_length = 20)
    password = forms.CharField(label = 'Password', max_length = 20)

class AddTaskForm(forms.Form):
    task_name = forms.CharField(label = 'task_name', max_length = 50)
    description = forms.CharField(label = 'description', max_length = 200)

class UpdateTaskForm(forms.Form):
    task_name = forms.CharField(label = 'task_name', max_length = 50)
    description = forms.CharField(label = 'description', max_length = 200)
    status = forms.CharField(label = 'status', max_length = 50)

class RegisterForm(forms.Form):
    username = forms.CharField(label = 'username', max_length = 20)
    firstname = forms.CharField(label = 'firstname', max_length = 20)
    lastname = forms.CharField(label = 'lastname', max_length = 20)
    email = forms.CharField(label = 'email', max_length = 100)
    password = forms.CharField(label = 'password', max_length = 20)
    confirm_password = forms.CharField(label = 'confirm_password', max_length = 20)

activity/todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

from .models import ToDoItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm

# Create your views here.
def index(request):
    todoitem_list = ToDoItem.objects.filter(user_id = request.user.id)
    context = { 
        'todoitem_list': todoitem_list,
        'user': request.user,
    }
    return render(request, 'todolist/index.html', context)

def todoitem(request, todoitem_id):
    object = get_object_or_404(ToDoItem, pk = todoitem_id)
    todoitem = model_to_dict(object)
    return render(request, 'todolist/todoitem.html', todoitem)

def register(request):
    template = 'todolist/register.html'
    
    context = {
        'is_registered': False,
        'is_successful': False,
        'password_different': False,
    }

    if request.method == 'GET':
        return render(request, template, context)
    
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if not form.is_valid():
            form = RegisterForm()
        else:
            context['username'] = form.cleaned_data['username']
            context['firstname'] = form.cleaned_data['firstname']
            context['lastname'] = form.cleaned_data['lastname']
            context['email'] = form.cleaned_data['email']
            context['password'] = form.cleaned_data['password']
            context['confirm_password'] = form.cleaned_data['confirm_password']

            # Check if password and confirm password match
            if context['password'] != context['confirm_password']:
                context['password_different'] = True
                return render(request, template, context)
            
            try:
                user = User.objects.get(username = context['username'])
            except User.DoesNotExist:
                user = None

            if user is not None:
                context['is_registered'] = True
                return render(request, template, context)

            user = User(
                    username = context['username'],
                    first_name = context['firstname'], 
                    last_name = context['lastname'],
                    email = context['email'],
                    is_staff =  False,
                    is_active = True
                )
            user.set_password(context['password'])
            user.save()
            context = { 'is_successful': True }
            return render(request, template, context)
    

def change_password(request):
    template = 'todolist/change_password.html'
    is_user_authenticated = False

    user = authenticate(username = 'kimminjeong', password = 'P@ssw0rd789')
    if user is not None:
        user.set_password('P@ssw0rd')
        user.save()
        is_user_authenticated = True

    context = {
        'is_authenticated': is_user_authenticated
    }
    return render(request, template, context)

def login_view(request):
    context = { 'error': False }
    if request.method == 'POST':
        
        form = LoginForm(request.POST)
        if not form.is_valid():
            form = LoginForm()
        else:
            credentials = {
                'username': form.cleaned_data['username'],
                'password': form.cleaned_data['password'],
            }

            user = authenticate(**credentials)
            if user is not None:
                login(request, user)
                return redirect("todolist:index")
            else:
                context = { 'error': True }
    
    return render(request, 'todolist/login.html', context)

def logout_view(request):
    logout(request)
    return redirect('todolist:index')

def add_task(request):
    context = { 'error': False, 'user': request.user }
    if request.method == 'POST':

        form = AddTaskForm(request.POST)
        if not form.is_valid():
            form = AddTaskForm()
        else:
            task = {
                'task_name': form.cleaned_data['task_name'],
                'description': form.cleaned_data['description'],
                'date_created': timezone.now(),
            }
            
            duplicates = ToDoItem.objects.filter(task_name = task['task_name'])
            if not duplicates:
                ToDoItem.objects.create(**task, user_id = request.user.id)
                return redirect('todolist:index')
            else:
                context = { 'error': True }

    return render(request, 'todolist/add_task.html', context)

def update_task(request, todoitem_id):

    todoitem = ToDoItem.objects.get(pk = todoitem_id)
    context = { 
        'error': False, 'user': request.user,
        'todoitem_id': todoitem_id,
        'task_name': todoitem.task_name,
        'description': todoitem.description,
        'status': todoitem.status
    }

    if request.method == 'POST':
        form = UpdateTaskForm(request.POST)
        if not form.is_valid():
            form = UpdateTaskForm()
        else:
            task_name = form.cleaned_data['task_name']
            description = form.cleaned_data['description']
            status = form.cleaned_data['status']

            if todoitem:
                todoitem.task_name = task_name
                todoitem.description = description
                todoitem.status = status
                todoitem.save()
                return redirect('todolist:index')
            else:
                context = {
                    'error': True
                }

    return render(request, 'todolist/update_task.html', context)

def delete_task(request, todoitem_id):
    ToDoItem.objects.filter(pk = todoitem_id).delete()
    return redirect('todolist:index')

activity/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} To Do App {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}  

    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

activity/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'todolist:index' %}">To Do App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:add_task' %}">Add Task</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
          </li>
      </div>
    </div>
  </nav>

activity/todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}
    Add Task
{% endblock %}

{% block content %}
    {% if user.is_anonymous %}
        <h1 class="text-center my-3">You are not authorized to access this page.</h1>
        <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
    {% else %}
        <div class="container">
            <div class="row">
                <div class="col-6 offset-3">
                    <h1 class="text-center my-3">Add A Task</h1>
                    {% if error %}
                        <p class="text-danger text-center">Duplicate task found.</p>
                    {% endif %}
                </div>

                <form action="{% url 'todolist:add_task' %}" method="POST">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="task_name">Task Name: </label>
                        <input type="text" class="form-control" id="task_name" name="task_name" value="{{ task_name }}" maxlength="50" required>
                    </div>

                    <div class="mb-3">
                        <label for="description">Description: </label>
                        <input type="text" class="form-control" id="description" name="description" value="{{ description }}" maxlength="50" required>
                    </div>

                    <div class="tex-center">
                        <input type="submit" class="btn btn-success" value="Add Task">
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

activity/todolist/templates/todolist/change_password.html
{% if not is_authenticated %}
    <h1>Invalid User Credentials</h1>
    <p>Check if the username and password are correct.</p>
{% else %}
    <h1>User Password is successfully updated!</h1>
{% endif %}

activity/todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    {% if todoitem_list and not user.is_anonymous %}
            <h1 class="text-center my-3">Welcome {{user.last_name}} {{user.first_name}}</h1>
            <div class="containerr">
                <div class="row">
                    <h3 class="text-center mb-3">My Tasks</h3>
                    <ul class="list-group col-lg-2 offset-lg-5 text-center">
                        {% for todoitem in todoitem_list %}
                            <li class="list-group-item">
                                <a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">{{ todoitem.task_name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            
        {% elif user.is_anonymous %}
            <h1 class="text-center my-3">You are not authorized to access this page.</h1>
            <p class="text-center">Kindly login <a href="login/">here</a></p>
        {% elif todoitem_list.count == 0 and user %}
            <p>No Tasks have been created.</p>
        {%endif %}
{% endblock %}

activity/todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Login</h1>
            {% if error %}
                <p class="text-danger">Invalid user credentials, please check your username and password.</p>
            {% endif %}
            <form action="{% url 'todolist:login' %}" method="POST">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="username">Username: </label>
                    <input type="text" class="form-control" id="username" name="username" value="{{ username }}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="password">Password: </label>
                    <input type="password" class="form-control" id="password" name="password" value="{{ password }}" maxlength="20" required>
                </div>
                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="Login">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

activity/todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}
    Register
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center my-3">Register</h1>
            {% if is_registered %}
                <p class="text-danger text-center">A duplicate user has been found, user creation is unsuccessful.</p>
            {% elif is_successful %}
                <p class="text-success text-center">The account is successfully created!</p>
            {% elif password_different %}
                <p class="text-danger text-center">Password and Confirm Password are not the same.</p>
            {% endif %}
            <form action="{% url 'todolist:register' %}" method="POST">
                {% csrf_token %}

                <div class="mb-3">
                    <label for="username">Username: </label>
                    <input type="text" class="form-control" id="username" name="username" value="{{ username }}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="firstname">First Name: </label>
                    <input type="text" class="form-control" id="firstname" name="firstname" value="{{ firstname }}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="lastname">Last Name: </label>
                    <input type="text" class="form-control" id="lastname" name="lastname" value="{{ lastname }}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="email">Email: </label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ email }}" maxlength="100" required>
                </div>
                <div class="mb-3">
                    <label for="password">Password: </label>
                    <input type="password" class="form-control" id="password" name="password" value="{{ password }}" maxlength="20" required>
                </div>
                <div class="mb-3">
                    <label for="confirm_password">Confirm Password: </label>
                    <input type="password" class="form-control" id="confirm_password" name="confirm_password" value="{{ confirm_password }}" maxlength="20" required>
                </div>
                <div class="text-center">
                    <input class="btn btn-success" type="submit" value="Register">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

activity/todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}
    Todo Item
{% endblock %}

{% block content %}
<div class="text-center my-3">
    <h1>{{task_name}}</h1>
    <h3>Description</h3>
    <p>{{description}}</p>
    <h3>Status</h3>
    <p>{{status}}</p>

    <button class="btn btn-primary mx-1 text-decoration-none">
        <a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
    </button>

    <button class="btn btn-danger mx-1 text-decoration-none">
        <a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
    </button>

    <button class="btn btn-warning mx-1 text-decoration-none">
        <a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back to Tasks</a>
    </button>

</div>
{% endblock %}

activity/todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}
    Update Task
{% endblock %}

{% block content %}
    {% if not user.is_anonymous %}
        <div class="container">
            <div class="row">
                <div class="col-6 offset-3">
                    <h1 class="text-center my-3">
                        Update Task
                    </h1>
                    {% if error %}
                        <p class="text-center text-danger">Task not found.</p>
                    {% endif %}
                    <form action="{% url 'todolist:update_task' todoitem_id %}" method="POST">
                        {% csrf_token %}
    
                        <div class="mb-3">
                            <label for="task_name">Task Name: </label>
                            <input type="text" class="form-control" id="task_name" name="task_name" value="{{ task_name }}" maxlength="50" required>
                        </div>
    
                        <div class="mb-3">
                            <label for="description">Description: </label>
                            <input type="text" class="form-control" id="description" name="description" value="{{ description }}" maxlength="50" required>
                        </div>

                        <div class="mb-3">
                            <label for="status">Status: </label>
                            <input type="text" class="form-control" id="status" name="status" value="{{ status }}" maxlength="50" required>
                        </div>
    
                        <div class="tex-center">
                            <input type="submit" class="btn btn-success" value="Update Task">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% else %}
            <h1 class="text-center my-3">You are not authorized to access this page.</h1>
            <p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
    {% endif %}

{% endblock %}